import admin from 'firebase-admin';
import crypto from 'node:crypto';
import { PRODUCT_SEED, SERVICE_SEED, CLASS_SEED } from '../../catalog.js';
import { DEFAULT_SITE } from '../../config.js';
import { orderConfirmation, adminOrder, bookingConfirmation, adminBooking, classConfirmation, adminClass, statusEmail, subscriberEmail, contactAck, adminContact } from './email-templates.mjs';

const env=name => process.env[name] || '';
const clean=(value,max=300)=>String(value ?? '').trim().slice(0,max);
const money=value=>Math.round(Number(value || 0) * 100) / 100;
const json=(status,payload)=>new Response(JSON.stringify(payload),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
function pathOf(req){let path=new URL(req.url).pathname;if(path.startsWith('/api'))path=path.slice(4);if(path.startsWith('/.netlify/functions/cisca'))path=path.slice('/.netlify/functions/cisca'.length);return path.replace(/\/+$/,'')||'/';}
async function body(req){try{return await req.json()}catch{return{}}}
function db(){if(!admin.apps.length){let credential;if(env('FIREBASE_SERVICE_ACCOUNT')||env('FIREBASE_SERVICE_ACCOUNT_JSON')){credential=admin.credential.cert(JSON.parse(env('FIREBASE_SERVICE_ACCOUNT')||env('FIREBASE_SERVICE_ACCOUNT_JSON')))}else{if(!env('FIREBASE_PROJECT_ID')||!env('FIREBASE_CLIENT_EMAIL')||!env('FIREBASE_PRIVATE_KEY'))throw Error('Firebase Admin environment variables are missing.');credential=admin.credential.cert({projectId:env('FIREBASE_PROJECT_ID'),clientEmail:env('FIREBASE_CLIENT_EMAIL'),privateKey:env('FIREBASE_PRIVATE_KEY').replace(/\\n/g,'\n')});}admin.initializeApp({credential});}return admin.firestore();}
async function authAdmin(req){db();const token=clean(req.headers.get('authorization')).replace(/^Bearer\s+/i,'');if(!token)throw Error('Admin authentication required.');const decoded=await admin.auth().verifyIdToken(token);const allowed=env('ADMIN_EMAILS').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(!allowed.length)throw Error('No admin email is configured.');if(!allowed.includes(String(decoded.email||'').toLowerCase()))throw Error('This account is not approved for admin.');return decoded;}
async function resend(to,email){if(!env('RESEND_API_KEY')||!to)return;const from=env('EMAIL_FROM')||'Cisca Makeovers <onboarding@resend.dev>';const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env('RESEND_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject:email.subject,html:email.html,text:email.text})});if(!response.ok)console.error('Resend error',await response.text());}
const adminEmail=()=>env('ADMIN_EMAIL')||env('RESEND_ADMIN_EMAIL');
const code=prefix=>`${prefix}-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
const token=()=>crypto.randomBytes(24).toString('hex');
async function publicList(collection,fallback=[]){const snap=await db().collection(collection).get();if(snap.empty)return fallback;return snap.docs.map(d=>({id:d.id,...d.data()}));}
async function getSettings(){const snap=await db().collection('settings').doc('public').get();return {...DEFAULT_SITE,...(snap.exists?snap.data():{})};}
async function paystackInit({email,amount,reference,callbackUrl,metadata}){if(!env('PAYSTACK_SECRET_KEY'))throw Error('Paystack is not configured.');const response=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${env('PAYSTACK_SECRET_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify({email,amount:Math.round(amount*100),currency:'GHS',reference,callback_url:callbackUrl,metadata})});const data=await response.json();if(!response.ok||!data.status)throw Error(data.message||'Could not initialize payment.');return data.data;}
async function paystackVerify(reference){if(!env('PAYSTACK_SECRET_KEY'))throw Error('Paystack is not configured.');const response=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${env('PAYSTACK_SECRET_KEY')}`}});const data=await response.json();if(!response.ok||!data.status)throw Error(data.message||'Could not verify payment.');return data.data;}
function callback(req){const origin=env('SITE_URL')||new URL(req.url).origin;return `${origin.replace(/\/$/,'')}/success.html`;}
function durationMinutes(service){const text=String(service?.duration||'90 min').toLowerCase();const hours=Number(text.match(/(\d+(?:\.\d+)?)\s*hr/)?.[1]||0);const mins=Number(text.match(/(\d+)\s*min/)?.[1]||0);return Math.max(30,Math.round(hours*60+mins)||90);}
function bookingDuration(services=[]){return Math.max(30,services.reduce((total,service)=>total+durationMinutes(service),0)||90);}
function timeMinutes(value){const [hours,mins]=String(value||'').split(':').map(Number);return Number.isFinite(hours)&&Number.isFinite(mins)?hours*60+mins:-1;}
function bookingBlocksSlot(row){if(row.status==='cancelled')return false;if(row.paymentStatus==='paid')return true;if(row.paymentStatus!=='pending')return false;const created=row.createdAt?.toDate?.()||null;return created?Date.now()-created.getTime()<20*60*1000:false;}
async function bookingsForDate(date){const snap=await db().collection('bookings').where('date','==',date).get();return snap.docs.map(d=>({id:d.id,...d.data()})).filter(bookingBlocksSlot);}
async function assertBookingSlot(date,time,duration){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Choose a valid appointment date.');if(!/^\d{2}:\d{2}$/.test(time))throw Error('Choose a valid appointment time.');const start=timeMinutes(time),end=start+duration;if(start<0)throw Error('Choose a valid appointment time.');const rows=await bookingsForDate(date);for(const row of rows){const rowStart=timeMinutes(row.time),rowEnd=rowStart+bookingDuration(row.services||[]);if(rowStart>=0&&start<rowEnd&&end>rowStart)throw Error('That appointment time has just been taken. Please choose another available time.');}}
async function monthAvailability(month){if(!/^\d{4}-\d{2}$/.test(month))throw Error('Choose a valid month.');const [year,mon]=month.split('-').map(Number);const first=`${month}-01`,lastDay=new Date(year,mon,0).getDate(),last=`${month}-${String(lastDay).padStart(2,'0')}`;const availability=await publicList('availability',[]);const closedDates=availability.filter(x=>x.open===false&&String(x.date||x.id)>=first&&String(x.date||x.id)<=last).map(x=>String(x.date||x.id));const snap=await db().collection('bookings').where('date','>=',first).where('date','<=',last).get();const busy={};for(const doc of snap.docs){const row={id:doc.id,...doc.data()};if(!bookingBlocksSlot(row))continue;(busy[row.date]??=[]).push({time:row.time,duration:bookingDuration(row.services||[])});}return {month,closedDates,busy};}
async function startBooking(req,p){const serviceIds=Array.isArray(p.serviceIds)?p.serviceIds.map(clean):[];if(!serviceIds.length)throw Error('Choose at least one service.');const configured=await publicList('services',SERVICE_SEED);const services=serviceIds.map(id=>configured.find(service=>service.id===id&&service.active!==false)).filter(Boolean);if(services.length!==serviceIds.length)throw Error('One selected service is not available.');const date=clean(p.date),time=clean(p.time);const availability=await db().collection('availability').doc(date).get();if(availability.exists&&availability.data().open===false)throw Error('That date is not available for appointments.');await assertBookingSlot(date,time,bookingDuration(services));const total=money(services.reduce((sum,service)=>sum+Number(service.price||0),0));if(total<=0)throw Error('Booking price is not configured.');const paymentOption=p.paymentOption==='deposit'?'deposit':'full';const amount=paymentOption==='deposit'?money(total/2):total;const reference=`CMBOOK-${Date.now()}-${crypto.randomBytes(2).toString('hex')}`;const ref=db().collection('bookings').doc();const inspoImages=Array.isArray(p.inspoImages)?p.inspoImages.filter(url=>/^https:\/\/(res\.cloudinary\.com|images\.unsplash\.com)\//.test(String(url))).slice(0,4):[];const record={bookingNumber:code('CMB'),client:{firstName:clean(p.firstName),lastName:clean(p.lastName),email:clean(p.email).toLowerCase(),phone:clean(p.phone)},services,date,time,locationType:clean(p.locationType),address:clean(p.address,500),occasion:clean(p.occasion),notes:clean(p.notes,1200),inspoImages,total,amountDue:amount,paymentOption,paymentStatus:'pending',status:'pending',reference,createdAt:admin.firestore.FieldValue.serverTimestamp()};await ref.set(record);await db().collection('payments').doc(reference).set({kind:'booking',recordId:ref.id,expectedAmount:amount,status:'pending'});let pay;try{pay=await paystackInit({email:record.client.email,amount,reference,callbackUrl:callback(req),metadata:{kind:'booking',recordId:ref.id}});}catch(error){await Promise.allSettled([ref.delete(),db().collection('payments').doc(reference).delete()]);throw error;}return json(200,{authorizationUrl:pay.authorization_url,reference});}
async function startClass(req,p){const classes=await publicList('classes',CLASS_SEED);const item=classes.find(x=>x.id===clean(p.classId));if(!item||!item.available||item.price==null)throw Error('Registration for this class is not open.');const amount=money(item.price),reference=`CMCLASS-${Date.now()}-${crypto.randomBytes(2).toString('hex')}`,ref=db().collection('registrations').doc(),record={registrationNumber:code('CMA'),student:{firstName:clean(p.firstName),lastName:clean(p.lastName),email:clean(p.email).toLowerCase(),phone:clean(p.phone)},experience:clean(p.experience),goals:clean(p.goals,1200),classId:item.id,classTitle:item.title,amountDue:amount,paymentStatus:'pending',status:'pending',reference,createdAt:admin.firestore.FieldValue.serverTimestamp()};await ref.set(record);await db().collection('payments').doc(reference).set({kind:'class',recordId:ref.id,expectedAmount:amount,status:'pending'});let pay;try{pay=await paystackInit({email:record.student.email,amount,reference,callbackUrl:callback(req),metadata:{kind:'class',recordId:ref.id}});}catch(error){await Promise.allSettled([ref.delete(),db().collection('payments').doc(reference).delete()]);throw error;}return json(200,{authorizationUrl:pay.authorization_url,reference});}
async function startOrder(req,p){const items=Array.isArray(p.items)?p.items:[];if(!items.length)throw Error('Your bag is empty.');const docs=await Promise.all(items.map(item=>db().collection('products').doc(clean(item.id)).get()));const built=items.map((item,index)=>{const doc=docs[index];if(!doc.exists)throw Error('A product in your bag is no longer available.');const product={id:doc.id,...doc.data()},qty=Math.max(1,Math.min(20,Number(item.qty||1)));if(!product.available||product.price==null)throw Error(`${product.name||'A product'} is not available to purchase.`);return{id:product.id,name:product.name,category:product.category,price:Number(product.price),qty,image:product.image||''};});const total=money(built.reduce((sum,item)=>sum+item.price*item.qty,0));const customer=p.customer||{};if(!clean(customer.email))throw Error('Email address is required.');const reference=`CMORDER-${Date.now()}-${crypto.randomBytes(2).toString('hex')}`,ref=db().collection('orders').doc(),record={orderNumber:code('CM'),customer:{firstName:clean(customer.firstName),lastName:clean(customer.lastName),email:clean(customer.email).toLowerCase(),phone:clean(customer.phone),address:clean(customer.address,500),city:clean(customer.city),region:clean(customer.region),note:clean(customer.deliveryNotes||customer.note,500)},items:built,total,paymentStatus:'pending',status:'pending',trackingToken:token(),reference,createdAt:admin.firestore.FieldValue.serverTimestamp()};await ref.set(record);await db().collection('payments').doc(reference).set({kind:'order',recordId:ref.id,expectedAmount:total,status:'pending'});let pay;try{pay=await paystackInit({email:record.customer.email,amount:total,reference,callbackUrl:callback(req),metadata:{kind:'order',recordId:ref.id}});}catch(error){await Promise.allSettled([ref.delete(),db().collection('payments').doc(reference).delete()]);throw error;}return json(200,{authorizationUrl:pay.authorization_url,reference});}
async function verifyPayment(reference){reference=clean(reference,150);if(!reference)throw Error('Payment reference is missing.');const paymentRef=db().collection('payments').doc(reference),paymentSnap=await paymentRef.get();if(!paymentSnap.exists)throw Error('Payment reference is not linked to a Cisca transaction.');const payment=paymentSnap.data(),pay=await paystackVerify(reference);if(pay.status!=='success')throw Error('Payment has not completed successfully.');if(String(pay.currency||'').toUpperCase()!=='GHS')throw Error('Payment currency could not be verified.');if(Number(pay.amount)!==Math.round(Number(payment.expectedAmount||0)*100))throw Error('Payment amount could not be verified.');const collection=payment.kind==='order'?'orders':payment.kind==='booking'?'bookings':'registrations',recordRef=db().collection(collection).doc(payment.recordId),snap=await recordRef.get();if(!snap.exists)throw Error('Transaction record was not found.');const before=snap.data(),alreadyPaid=before.paymentStatus==='paid',status=before.status==='pending'?'confirmed':before.status,paidRecord={...before,paymentStatus:'paid',status,amountPaid:money(Number(pay.amount)/100),paidAt:admin.firestore.FieldValue.serverTimestamp()};await recordRef.update(paidRecord);await paymentRef.set({status:'paid',verifiedAt:admin.firestore.FieldValue.serverTimestamp(),gatewayReference:clean(pay.reference,150)},{merge:true});const current={id:recordRef.id,...before,paymentStatus:'paid',status,amountPaid:money(Number(pay.amount)/100)};if(!alreadyPaid){if(payment.kind==='order')await Promise.allSettled([resend(current.customer?.email,orderConfirmation(current)),resend(adminEmail(),adminOrder(current))]);else if(payment.kind==='booking')await Promise.allSettled([resend(current.client?.email,bookingConfirmation(current)),resend(adminEmail(),adminBooking(current))]);else await Promise.allSettled([resend(current.student?.email,classConfirmation(current)),resend(adminEmail(),adminClass(current))]);}return{kind:payment.kind,record:current};}
function serial(value){if(!value)return value;if(typeof value.toDate==='function')return value.toDate().toISOString();if(Array.isArray(value))return value.map(serial);if(typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,serial(item)]));return value;}
async function docs(collection,limit=300){const snap=await db().collection(collection).orderBy('createdAt','desc').limit(limit).get().catch(()=>db().collection(collection).limit(limit).get());return snap.docs.map(doc=>serial({id:doc.id,...doc.data()}));}
function verifyWebhook(signature,raw){if(!signature||!env('PAYSTACK_SECRET_KEY'))return false;const expected=crypto.createHmac('sha512',env('PAYSTACK_SECRET_KEY')).update(raw).digest('hex');const actual=Buffer.from(String(signature),'utf8');const expectedBuffer=Buffer.from(expected,'utf8');return actual.length===expectedBuffer.length&&crypto.timingSafeEqual(expectedBuffer,actual);}

export default async req=>{try{const path=pathOf(req),method=req.method;
  if(method==='GET'&&path==='/settings')return json(200,{settings:await getSettings()});
  if(method==='GET'&&path==='/services')return json(200,{services:await publicList('services',SERVICE_SEED)});
  if(method==='GET'&&path==='/classes')return json(200,{classes:await publicList('classes',CLASS_SEED)});
  if(method==='GET'&&path==='/products')return json(200,{products:await publicList('products',[])});
  if(method==='GET'&&path==='/availability'){const url=new URL(req.url),month=clean(url.searchParams.get('month')),date=clean(url.searchParams.get('date'));if(month)return json(200,await monthAvailability(month));if(!date)return json(200,{open:true});const availability=await db().collection('availability').doc(date).get(),busy=await bookingsForDate(date);return json(200,{...(availability.exists?serial({id:availability.id,...availability.data()}):{date,open:true}),busy:busy.map(row=>({time:row.time,duration:bookingDuration(row.services||[])}))});}
  if(method==='GET'&&path==='/product'){const id=clean(new URL(req.url).searchParams.get('id'));const snap=await db().collection('products').doc(id).get();return json(200,{product:snap.exists?serial({id:snap.id,...snap.data()}):null});}
  if(method==='POST'&&path==='/booking/inspo-sign'){if(!env('CLOUDINARY_CLOUD_NAME')||!env('CLOUDINARY_API_KEY')||!env('CLOUDINARY_API_SECRET'))throw Error('Image upload is not configured.');const timestamp=Math.floor(Date.now()/1000),folder='cisca-inspo';const signature=crypto.createHash('sha1').update(`folder=${folder}&timestamp=${timestamp}${env('CLOUDINARY_API_SECRET')}`).digest('hex');return json(200,{cloudName:env('CLOUDINARY_CLOUD_NAME'),apiKey:env('CLOUDINARY_API_KEY'),timestamp,folder,signature});}
  if(method==='POST'&&path==='/booking/start')return await startBooking(req,await body(req));
  if(method==='POST'&&path==='/class/start')return await startClass(req,await body(req));
  if(method==='POST'&&path==='/order/start')return await startOrder(req,await body(req));
  if(method==='GET'&&path==='/payment/verify')return json(200,await verifyPayment(clean(new URL(req.url).searchParams.get('reference'))));
  if(method==='POST'&&path==='/payment/webhook'){const raw=await req.text();if(!verifyWebhook(req.headers.get('x-paystack-signature')||'',raw))return json(401,{error:'Invalid webhook signature.'});let event;try{event=JSON.parse(raw)}catch{return json(400,{error:'Invalid webhook payload.'})}if(event.event==='charge.success'&&event.data?.reference){await verifyPayment(clean(event.data.reference,150));}return json(200,{ok:true});}
  if(method==='POST'&&path==='/subscribe'){const b=await body(req),email=clean(b.email).toLowerCase();if(!email.includes('@'))throw Error('Enter a valid email address.');await db().collection('subscribers').doc(email).set({email,createdAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});await Promise.allSettled([resend(email,subscriberEmail()),resend(adminEmail(),{subject:'New Cisca subscriber',text:`${email} subscribed.`,html:`<p>${email} subscribed to the Cisca list.</p>`})]);return json(200,{ok:true});}
  if(method==='POST'&&path==='/contact'){const b=await body(req),message={name:clean(b.name),email:clean(b.email).toLowerCase(),phone:clean(b.phone),topic:clean(b.topic||b.subject),message:clean(b.message,3000)};if(!message.email||!message.message)throw Error('Email and message are required.');await db().collection('messages').add({...message,createdAt:admin.firestore.FieldValue.serverTimestamp()});await Promise.allSettled([resend(message.email,contactAck(message)),resend(adminEmail(),adminContact(message))]);return json(200,{ok:true});}
  if(method==='GET'&&path==='/track'){const url=new URL(req.url),order=clean(url.searchParams.get('order')).toUpperCase(),email=clean(url.searchParams.get('email')).toLowerCase(),phone=clean(url.searchParams.get('phone'));if(!order||(!email&&!phone))throw Error('Enter your order number and checkout email or phone number.');const snap=await db().collection('orders').where('orderNumber','==',order).limit(1).get();if(snap.empty)throw Error('We could not find an order with those details.');const orderRecord=serial({id:snap.docs[0].id,...snap.docs[0].data()});if(email&&String(orderRecord.customer?.email||'').toLowerCase()!==email)throw Error('We could not find an order with those details.');if(phone&&String(orderRecord.customer?.phone||'').replace(/\D/g,'')!==phone.replace(/\D/g,''))throw Error('We could not find an order with those details.');return json(200,{order:orderRecord});}
  if(method==='GET'&&path==='/track-token'){const tracking=clean(new URL(req.url).searchParams.get('token'),100),snap=await db().collection('orders').where('trackingToken','==',tracking).limit(1).get();if(snap.empty)throw Error('This tracking link is not valid.');return json(200,{order:serial({id:snap.docs[0].id,...snap.docs[0].data()})});}
  if(path.startsWith('/admin/')){await authAdmin(req);
    if(method==='GET'&&path==='/admin/dashboard')return json(200,{orders:await docs('orders'),bookings:await docs('bookings'),registrations:await docs('registrations'),products:await publicList('products',PRODUCT_SEED),classes:await publicList('classes',CLASS_SEED),services:await publicList('services',SERVICE_SEED),messages:await docs('messages'),subscribers:await docs('subscribers'),availability:await publicList('availability',[]),settings:await getSettings()});
    if(method==='POST'&&path==='/admin/seed'){const b=await body(req);for(const [collection,list] of [['products',b.products||[]],['services',b.services||[]],['classes',b.classes||[]]]){const rows=list.length?list:(collection==='products'?PRODUCT_SEED:collection==='services'?SERVICE_SEED:CLASS_SEED);for(const item of rows){const id=clean(item.id);if(!id)continue;const ref=db().collection(collection).doc(id),existing=await ref.get();if(!existing.exists)await ref.set({...item,updatedAt:admin.firestore.FieldValue.serverTimestamp()});}}return json(200,{ok:true});}
    if(method==='POST'&&path==='/admin/settings'){const b=await body(req),allowed=['brand','tagline','heroKicker','heroTitle','heroText','locationLabel','phoneDisplay','whatsapp','instagram','youtube','pinterest','footerText'];const cleanSettings=Object.fromEntries(allowed.map(key=>[key,clean(b[key],700)]));await db().collection('settings').doc('public').set(cleanSettings,{merge:true});return json(200,{ok:true,settings:await getSettings()});}
    if(method==='POST'&&['/admin/product','/admin/class','/admin/service'].includes(path)){const b=await body(req),collection=path.endsWith('/product')?'products':path.endsWith('/class')?'classes':'services',id=clean(b.id);if(!id)throw Error('Record ID is required.');const payload={...b};delete payload.id;await db().collection(collection).doc(id).set({...payload,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return json(200,{ok:true});}
    if(method==='POST'&&path==='/admin/availability'){const b=await body(req),date=clean(b.date);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('A valid date is required.');await db().collection('availability').doc(date).set({date,open:b.open!==false,note:clean(b.note),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return json(200,{ok:true});}
    if(method==='POST'&&path==='/admin/cloudinary-sign'){if(!env('CLOUDINARY_CLOUD_NAME')||!env('CLOUDINARY_API_KEY')||!env('CLOUDINARY_API_SECRET'))throw Error('Cloudinary is not configured.');const timestamp=Math.floor(Date.now()/1000),folder='cisca-products';const signature=crypto.createHash('sha1').update(`folder=${folder}&timestamp=${timestamp}${env('CLOUDINARY_API_SECRET')}`).digest('hex');return json(200,{cloudName:env('CLOUDINARY_CLOUD_NAME'),apiKey:env('CLOUDINARY_API_KEY'),timestamp,folder,signature});}
    if(method==='POST'&&path==='/admin/status'){const b=await body(req),kind=clean(b.kind),collection=kind==='order'?'orders':'bookings',id=clean(b.id),snap=await db().collection(collection).doc(id).get();if(!snap.exists)throw Error('Record not found.');const status=clean(b.status);await db().collection(collection).doc(id).update({status,updatedAt:admin.firestore.FieldValue.serverTimestamp()});const record={id:snap.id,...snap.data(),status};const email=kind==='order'?record.customer?.email:record.client?.email;await resend(email,statusEmail(kind,record));return json(200,{ok:true});}
  }
  return json(404,{error:'Not found'});
}catch(error){console.error(error);return json(/authentication|required|approved|admin email|webhook/i.test(error.message||'')?401:400,{error:error.message||'Request failed'});}}
