import { CISCA_CONFIG } from './config.js';
const header=`<div class="announcement">Studio appointments · Academy training · Beauty essentials</div><header class="site-header"><div class="wrap nav-row"><nav class="nav-links" aria-label="Main navigation"><a href="shop.html">Shop</a><a href="services.html">Services</a><a href="academy.html">Academy</a><a href="gallery.html">Portfolio</a></nav><button class="menu-btn" data-menu aria-label="Open menu">☰</button><a class="brand" href="index.html">Cisca Makeovers<small>Accra, Ghana</small></a><nav class="nav-actions"><a href="track.html">Track order</a><a href="booking.html">Book</a><a href="cart.html" class="cart-link">Bag <span class="cart-count" data-cart-count>0</span></a></nav></div></header><div class="mobile-menu" data-mobile-menu><a href="shop.html">Shop beauty</a><a href="services.html">Beauty services</a><a href="booking.html">Book appointment</a><a href="academy.html">Cisca Academy</a><a href="gallery.html">Portfolio</a><a href="track.html">Track order</a><a href="contact.html">Contact</a><div class="mobile-meta"><a href="https://wa.me/${CISCA_CONFIG.whatsapp}">WhatsApp</a><a href="${CISCA_CONFIG.instagram}">Instagram</a></div></div>`;
const footer=`<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div class="footer-brand"><h2>Cisca Makeovers</h2><p>Beauty services, hands-on education and professional beauty essentials from Accra.</p><form class="newsletter" data-newsletter><input type="email" name="email" required placeholder="Email address"><button type="submit">Join</button></form></div><div class="footer-col"><h3>Studio</h3><a href="services.html">Services</a><a href="booking.html">Book appointment</a><a href="gallery.html">Portfolio</a></div><div class="footer-col"><h3>Discover</h3><a href="academy.html">Academy</a><a href="shop.html">Shop</a><a href="track.html">Track order</a></div><div class="footer-col"><h3>Follow</h3><a href="contact.html">Contact</a><a href="${CISCA_CONFIG.instagram}" target="_blank">Instagram</a><a href="https://wa.me/${CISCA_CONFIG.whatsapp}" target="_blank">WhatsApp</a><a href="${CISCA_CONFIG.youtube}" target="_blank">YouTube</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Cisca Makeovers</span><span>Accra, Ghana</span></div></div></footer>`;
document.querySelector('[data-site-header]')?.insertAdjacentHTML('afterbegin',header);document.querySelector('[data-site-footer]')?.insertAdjacentHTML('afterbegin',footer);
const menu=document.querySelector('[data-mobile-menu]');document.querySelector('[data-menu]')?.addEventListener('click',()=>{menu?.classList.toggle('open');document.body.classList.toggle('nav-open',menu?.classList.contains('open'))});
export function getCart(){try{return JSON.parse(localStorage.getItem('cisca_cart')||'[]')}catch{return[]}}export function saveCart(cart){localStorage.setItem('cisca_cart',JSON.stringify(cart));updateCartCount()}export function updateCartCount(){const count=getCart().reduce((n,i)=>n+Number(i.qty||1),0);document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count)}updateCartCount();
export function toast(message){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el)}el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
export async function api(path,options={}){const res=await fetch(`${CISCA_CONFIG.apiBase}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Something went wrong');return data}
document.querySelectorAll('[data-newsletter]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button');btn.disabled=true;try{await api('/subscribe',{method:'POST',body:JSON.stringify({email:new FormData(form).get('email')})});form.reset();toast('Thanks for joining.')}catch(err){toast(err.message)}finally{btn.disabled=false}}));
